### ISSUE TITLE
How **Writership** prevent data race?

### ISSUE THREAD

**Issue by damphat** [phucvin/Writership#2]
Quote: "A field should only have one mutation/write/change place in code"

This idea sounds interesting, but I need a little more explanation.
If **2 threads** mutate a field at the same time. These 2 mutate calls have the **same StackTrace**, and they may also cause a **race condition**.

So how **Writership** prevent **data race** in this case?

**Comment by phucvin** [comment]
The writership alone is not enough to prevent data race, actually it is just a simple helper that can be disabled in production mode.
But the engine, which creates fields, is in charge for checking if 2 mutations happen to a same field in a cycle (i.e. Unity/game frame or calling to engine.Update). So, if 2 threads with even same stack trace write to a same field in a cycle, the engine will throw exception.
And with this library, you don't need to spawn thread manually. Just mark some code blocks that they can run in worker thread (i.e. no call to Unity API), and the engine will run them in parallel each cycle.

Side note, the library is called Writership, but the Writership class, is just a helper and not even public. Writership is there to help saving the last mutation's stack trace and compare with current mutation's stack trace, show these stack traces if they're different, for easier debugging/tracing.

Hope this explanation helps, for now. And in the future, when the library is stable enough, documentation on how to use and how it works will explain better.
